### ISSUE TITLE
Заполнить вторую таблицу.

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorgGames/metamod-r-temp#7]
Исходя из [этого](https://github.com/theAsmodai/metamod-r/blob/master/metamod/src/game_support.cpp) массива данных необходимо заполнить таблицу на [этой](https://github.com/EpicMorgGames/metamod-r-game-tests/wiki/Устранение-проблем) странице.

Если у игры есть бета версия, или legacy - то делаем еще одну строку. 

Если это альтернативный бинарик, например как  BugFixedHL - делаем отдельную строку.

Таблица-шаблон уже есть.

Если нету бинарика, то пишем :х: -> :x:

Пример:

| Игра \ Мод| Папка| Windows  | Linux 
| ------------- |----| ------| ------|
HL Decay | decay | hl.dll |  :x:
... | ...| ... | ...
Sven Coop (Old) | svencoop | hl.dll | hl.so
Sven Coop (Steam) |svencoop | server.dll | server.so

**Comment by Aleks-Z** [comment]
Заполнил. Также отсортировал по порядку как в metamod'e по алфавитному порядку названий папок модов.

**Comment by stamepicmorg** [comment]
Пасиб, молодец!
